### ISSUE TITLE
Anything with "fi" gets unindented, even if not scoped inside of an "if"

### ISSUE THREAD

**Issue by envygeeks** [atom/language-shellscript#101]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When typing anything with "fi" inside of Atom editor, with the Shellscript language enabled, it gets unindented to the next level.  Which forces you to have to go to the beginning of the line and properly indent it.

### Steps to Reproduce

1. Open a file
2. Set syntax to `shellscript`
3. Press Tab
4. Type `fi`

**Expected behavior:**

It not to unindent until a space happens... and only if within the context of an `if`.  At minimum though I would expect it to wait until I finish typing and press space, because the find command is quite common in any shell script, this gets in the way quite a bit when working with scripts.

**Comment by 50Wliu** [comment]
> and only if within the context of an `if`

This part should be fixed if you start using the new tree-sitter grammar included with language-shellscript.

> not to unindent until a space happens

Is it common to have a space character after a `fi`?  It seems to me like `fi`s are usually at the end of the line, like so:
```bash
if [ -f /some/file ]; then
    echo "/some/file exists."
fi
```

**Comment by envygeeks** [comment]
> Is it common to have a space character after a fi?

It's not common to have a space (I was just waking up and hadn't had coffee yet sorry about that crazy nonsensical comment.) 😂 the space was me thinking "wait till I hit space for 'find' before doing it" but that doesn't make sense really.

**Comment by envygeeks** [comment]
Is there a guide or something that shows how to use "tree-sitter"? It seems that searching in packages doesn't help, or must I build, or use a specific version of Atom or...?

**Comment by 50Wliu** [comment]
I think it'll be shipping in Atom 1.25.0 beta, and there will be a setting for you to turn on in Settings -> Core (`Use Tree Sitter Parsers`).

**Comment by envygeeks** [comment]
Just updating to say that treesitter didn't fix this, when in the context of an if, when I start to type "fi" for "find" it unindents.
